Repository googleapis/nodejs-datalabeling, pull requests merged in 2019-05, with the labels that each got.

#17 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#18 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#19 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#21 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
  package.json
Labels: automerge, cla: yes, status: blocked

#22 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#23 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#14 chore: re-order template utils
  src/v1beta1/data_labeling_service_client.js
  synth.metadata
Labels: :rotating_light:, cla: yes

#25 fix: DEADLINE_EXCEEDED is no longer retried
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  src/v1beta1/data_labeling_service_client_config.json
  synth.metadata
Labels: cla: yes

#27 fix: DEADLINE_EXCEEDED retry code is idempotent
  src/v1beta1/data_labeling_service_client_config.json
  synth.metadata
Labels: cla: yes

#30 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#34 chore: release 1.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#36 refactor: drop dependency on lodash.merge and update links
  package.json
  src/v1beta1/data_labeling_service_client.js
  synth.metadata
Labels: cla: yes

#37 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#38 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#39 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#40 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
