Repository googleapis/nodejs-datalabeling, pull requests merged in 2020-07, with the labels that each got.

#195 build: use bazel build
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#196 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#198 fix: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#201 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/docs.cfg
  .kokoro/presubmit/node8/lint.cfg
  .kokoro/presubmit/node8/samples-test.cfg
  .kokoro/presubmit/node8/system-test-grpcjs.cfg
  .kokoro/presubmit/node8/system-test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#202 chore: update generated protos.js
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: none

#203 build: missing closing paren in publish script
  .kokoro/publish.sh
  synth.metadata
Labels: cla: yes, context: partial

#207 chore: add config files for cloud-rad for node.js, delete Node 8 templates
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#206 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes, context: none

#208 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#209 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#210 chore: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#211 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#212 build: update protos
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none

#213 docs: add links to the CHANGELOG from the README.md for Java and Node
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full
