Repository googleapis/nodejs-datalabeling, pull requests merged in 2020-11, with the labels that each got.

#229 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: datalabeling, automerge, cla: yes, context: full

#231 fix: do not modify options object, use defaultScopes
  package.json
  src/index.ts
  src/v1beta1/data_labeling_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: datalabeling, automerge, cla: yes

#233 build: adds additional namespaces to protos
  protos/google/cloud/datalabeling/v1beta1/annotation.proto
  protos/google/cloud/datalabeling/v1beta1/annotation_spec_set.proto
  protos/google/cloud/datalabeling/v1beta1/data_labeling_service.proto
  protos/google/cloud/datalabeling/v1beta1/data_payloads.proto
  protos/google/cloud/datalabeling/v1beta1/dataset.proto
  protos/google/cloud/datalabeling/v1beta1/evaluation.proto
  protos/google/cloud/datalabeling/v1beta1/evaluation_job.proto
  protos/google/cloud/datalabeling/v1beta1/human_annotation_config.proto
  protos/google/cloud/datalabeling/v1beta1/instruction.proto
  protos/google/cloud/datalabeling/v1beta1/operations.proto
  protos/protos.json
  src/v1beta1/data_labeling_service_client.ts
  synth.metadata
Labels: api: datalabeling, cla: yes, context: none

#236 fix(browser): check for fetch on window
  protos/protos.json
  src/v1beta1/data_labeling_service_client.ts
  synth.metadata
Labels: api: datalabeling, cla: yes, context: partial

#237 build: stop tracking generated files
  src/v1beta1/data_labeling_service_client.ts
  synth.metadata
Labels: api: datalabeling, cla: yes, context: none

#238 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: datalabeling, automerge, cla: yes, context: full
