Repository googleapis/nodejs-datalabeling, pull requests merged in 2020-05, with the labels that each got.

#180 feat: check status of long running operation by its name
  protos/protos.js
  src/v1beta1/data_labeling_service_client.ts
  synth.metadata
  test/gapic_data_labeling_service_v1beta1.ts
Labels: automerge, cla: yes

#182 fix: synth.py clean up for multiple version
  protos/protos.js
  src/index.ts
  synth.metadata
  synth.py
Labels: cla: yes

#183 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
